### ISSUE TITLE
Travis CI issue

### ISSUE THREAD

**Issue by yuchengdong** [berkeley-stat159/project-beta#114]
Hi @matthew-brett @rossbar @jarrodmillman , we are having these errors here with TravisCI build. Can you please give us some hints on solving these issues?
https://travis-ci.org/berkeley-stat159/project-beta/jobs/95743608

**Comment by matthew-brett** [comment]
I think what is happening is that you have a module called `io.py`.  When Python tries to import its own `io` module, it gets yours instead, and so it gets confused.   Try renaming `io.py` to something else - does that help?

**Comment by yuchengdong** [comment]
Thanks for replying Matthew. I don't think we even have a io.py in our code folder.

**Comment by matthew-brett** [comment]
I can't get the commit referred to by the build with errors : https://travis-ci.org/berkeley-stat159/project-beta/jobs/95743608  . It says `Commit d8dd1d0` but it looks like this has been deleted.  But, here's another build with the same error:

https://travis-ci.org/berkeley-stat159/project-beta/jobs/94669214

If you look at the code tree for the relevant commit, you'll see an `io.py` file: https://github.com/berkeley-stat159/project-beta/blob/0c79720e88ec148889419ca5189142b6b6949a62/code/utils/io.py

**Comment by yuchengdong** [comment]
Thanks Matthew, we have fixed the issue. I guess we have overlooked the file structure for this pull request. Really appreciate your help, have a good day!
