### ISSUE TITLE
Hard-coded absolute path in tagging gui

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-beta#27]
There is a hard-coded path in the tagging gui that will cause failures if people try to clone and run it.

I understand that this code may just be a work-in-progress; perhaps you're not even sure if you will use it in the final project --- that's okay, and if it is the case, feel free to ignore this issue.

**Comment by rishizsinha** [comment]
final use of gui in project is uncertain, but definitely fixed by changing path to be an argument to the python script!
