### ISSUE TITLE
meeting

### ISSUE THREAD

**Issue by jarrodmillman** [berkeley-stat159/project-beta#62]
I've been asking groups to communicate with me via GitHub, so I can track our conversations better.

So I am responding to your email

"My group members and I (Beta) are extremely busy this week as well. Next week is Thanksgiving break and most of us will be out of town, so we can't make Wednesday or Friday of next week. We noticed your commentary on our code and would love to schedule a meeting with you to discuss our project progress."

here.

Anyway, I tried to find someone on your team in class on Thursday (11/19) to schedule something, but it looks like no one from your team was in class.  I am pretty busy right now and have set up meetings with most of the groups.  I still have some time on Tuesday (11/24) from 14-16.  Would that work for you?

Matthew may offer office hours on Monday (11/23) from 14-16 as well.

**Comment by cxmo** [comment]
Hello Jarrod, 
Thank you so much for your response. We understand that you are extremely busy, and most of us that day had interviews/ full-time recruitment events so we couldn't attend class. I can make Tuesday from 2-4 pm. Raj, Steve, and Rishi will meet with Matthew tomorrow. Again, thank you for the help! 

- Cindy
