### ISSUE TITLE
Travis CI Failed - no module named Nibabel 

### ISSUE THREAD

**Issue by cxmo** [berkeley-stat159/project-beta#77]
No module named Nibabel: 
Would adding the following to .travis.yml solve the problem? 
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install python-nibabel

**Comment by rishizsinha** [comment]
i had added it to the requirements file, and pandas started working, but this didn't, but I just tried generalizing the version so that may work hopefully

**Comment by yuchengdong** [comment]
problems fixed, thanks @rishizsinha
